version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weatherdb-projekt-arbete-db
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=2gfv77f6
        - POSTGRES_DB=weatherdb-projekt-arbete
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local